p71=[
 "BIBLE p71 - 1 livres",
 [
  "1-MATTHIEU - 19 chapitres",
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  [
   "1:19:18",
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   "⟦λεγο⟧υ⟦σιν⟧ αυτ⟦ω⟧ οι μα⟦θηται⟧ ει ουτως εστιν αιτια το⟦υ⟧ ⟦α̅ν̅ο̅υ̅⟧ ⟦μετα⟧ της γυναικος ⟦ου⟧ ⟦συμφε⟧ρει γαμησαι",
   "ο δε ⟦ειπεν⟧ ⟦α⟧υτοις ου παντες χω⟦ρουσιν⟧ ↔",
   null,
   null,
   null,
   null,
   null,
   "↔ θε⟦λε⟧ις ε⟦ι⟧ς τη⟦ν⟧ ⟦ζωην⟧ εισελθειν τη⟦ρ⟧ε⟦ι⟧ ⟦τας⟧ ⟦εν⟧τολας",
   "λεγει αυτ⟦ω⟧ ⟦ποιας⟧ ο δε εφη το ου φ⟦ονευ⟧σης ου μοιχευσει⟦ς⟧ ↔"
  ]
 ]
]