p29=[
 "BIBLE p29 - 5 livres",
 null,
 null,
 null,
 null,
 [
  "5-ACTES - 26 chapitres",
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  [
   "5:26:20",
   null,
   null,
   null,
   null,
   null,
   null,
   "↔ το δωδεκ⟦αφυλον⟧ ⟦ημων⟧ ⟦εν⟧ ⟦εκτε⟧νια νυκτ⟦α⟧ ⟦και⟧ ⟦ημεραν⟧ ⟦λατρευον⟧ ελπιδι κ⟦αταντησαι⟧ ⟦περι⟧ ⟦ης⟧ ⟦ελπιδος⟧ ενκαλου⟦μαι⟧ ⟦υπο⟧ ⟦ιουδαιων⟧ ⟦βασιλευ⟧",
   "⟦ει⟧ ο θ̅ς̅ νεκρ⟦ους⟧ ↔",
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   "⟦α⟧λλα τοις ε⟦ν⟧ ⟦δαμασκω⟧ ⟦πρωτον⟧ ⟦τε⟧ ⟦και⟧ ⟦ιερο⟧σολομοις κα⟦ι⟧ ⟦της⟧ ⟦ιουδαιας⟧ ⟦και⟧ ⟦τοις⟧ ⟦εθνεσιν⟧ εκηρυξα ⟦μετανοειν⟧ ⟦και⟧ ⟦επιστρεφειν⟧ ⟦ε⟧πι τον θ̅ν̅ ⟦αξια⟧ ⟦της⟧ ⟦μετανοιας⟧ ⟦εργα⟧ ⟦πρ⟧ασσοντας"
  ]
 ]
]