p134=[
 "BIBLE p134 - 4 livres",
 null,
 null,
 null,
 [
  "4-JEAN - 2 chapitres",
  [
   "4:1:51",
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   "↔ τ⟦ου⟧ ⟦θ̅υ̅⟧ ⟦συ⟧ ⟦βασιλευς⟧ ⟦ει⟧ ⟦του⟧ ⟦ι̅σ̅λ̅⟧",
   "⟦απεκριθη⟧ ⟦ι̅ς̅⟧ ⟦και⟧ ⟦ειπεν⟧ ⟦αυ⟧τω οτ⟦ι⟧ ειπον σοι ⟦οτι⟧ ⟦ειδον⟧ ⟦σε⟧ ⟦υποκατω⟧ ⟦της⟧ ⟦συκης⟧ ⟦πιστευ⟧εις μειζω ⟦τουτων⟧ ⟦οψη⟧",
   "⟦και⟧ ⟦λεγει⟧ ⟦αυτω⟧ ⟦αμην⟧ ⟦αμην⟧ ⟦λεγω⟧ υμιν οψεσθε τον ο̅⟦̅υ̅⟧̅ρ̅ο̅⟦̅ν̅⟧̅ ⟦ανεωγοτα⟧ ⟦και⟧ ⟦τους⟧ ⟦αγγελους⟧ ⟦του⟧ θεου αναβα⟦ι⟧νοντας ⟦και⟧ ⟦καταβαινοντας⟧ ⟦επι⟧ ⟦τον⟧ υ̅ν̅ ⟦το⟧υ α̅ν̅⟦̅ο̅υ̅⟧̅"
  ],
  [
   "4:2:1",
   "και ⟦τη⟧ ⟦τρι⟧τη ↔"
  ]
 ]
]