p87=[
 "BIBLE p87 - 18 livres",
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 null,
 [
  "18-PHILEMON - 1 chapitres",
  [
   "18:1:25",
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   "↔ ⟦ι⟧να υπερ σου μ⟦οι⟧ ⟦διακονη⟧ ⟦εν⟧ τοις δεσμ⟦οις⟧ ⟦του⟧ ⟦ευαγγελιου⟧",
   "χωρις δε τη⟦ς⟧ ⟦σης⟧ ⟦γνωμης⟧ ⟦ο⟧υδεν ηθελη⟦σα⟧ ⟦ποιησαι⟧ ⟦ιν⟧α μη ως κατα ⟦αναγκην⟧ ⟦το⟧ ⟦αγα⟧θον σου η αλ⟦λα⟧ ⟦κατα⟧ ⟦εκουσιον⟧",
   "⟦ταχα⟧ ⟦γαρ⟧ δια τουτ⟦ο⟧ ⟦εχωρισθη⟧ ⟦προς⟧ ⟦ωρ⟧αν ι⟦να⟧ ⟦αιωνιον⟧ ⟦αυτον⟧ ↔",
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   "↔ ⟦λουκ⟧ας οι συνεργ⟦οι⟧ ⟦μου⟧",
   "⟦η⟧ ⟦χαρις⟧ ⟦μ⟧εθ υμων ↔"
  ]
 ]
]